### ISSUE TITLE
添加redis缓存

### ISSUE THREAD

**Issue by buttercannfly** [EricJeffrey/Lab418Site#8]
- 出于性能的考虑，在用户和数据库之间插入redis缓存作迅速反应
- 出于并发的考虑，在大并发情形下，所有的请求直接访问数据库会出现连接异常，插入redis以作缓冲

**Comment by EricJeffrey** [comment]
😅 出于想了解一下这玩意的考虑，JUST DO IT

**Comment by EricJeffrey** [comment]
closed by #3
