### ISSUE TITLE
文档增删改查接口

### ISSUE THREAD

**Issue by buttercannfly** [EricJeffrey/Lab418Site#9]
/doc GET 获取全部文档
/doc?title={] GET 获取单个文档 & 根据文档标题查询
/doc/delete?title={} GET 根据标题删除文档
/doc/add POST 增加文档
/doc/update POST 修改文档

**Comment by EricJeffrey** [comment]
`/doc/add`和`/doc/post`的参数是`{ title, paragraph, timestamp}`吧？那么`add`和`update`的时候需要更加明确一下接口返回值了，分开考虑:
1. add
    - 如果title已经存在返回什么？
    - 如果title
2. update

**Comment by EricJeffrey** [comment]
`/doc/add, /doc/post`的参数是`{ title, paragraph, timestamp}`吧？那么add和update的时候需要更加明确一下接口返回值了：

- update如果title不存在返回什么
- update后的title如果已经存在返回什么，毕竟title是唯一的
- add如果title已经存在返回什么？
- 如果是title或者paragraph空字符串要不要存，或者说前端要不要处理？

另外就是注意sql注入的情况了，不过springboot这种应该都防止了，可以看一下。
我想到的差不多就是这些了，主要是无法**正常**完成操作的时候，服务器程序给前端发送的错误码如何定义了。

**Comment by buttercannfly** [comment]
这样可不可以，update以及add的接口返回值定义为{code,message}字段，如果更新或者添加文档失败(title冲突)，code返回码设为400，message根据实际情况作出调整，比如说message="title already exists,add fail"；如果是title和paragraph为空，后台接收之后返回错误码402，message定义为"field must not be empty"，前端收到错误码后弹出自己的错误提示

**Comment by EricJeffrey** [comment]
嗯可以，空title或para这个前端做就可以，主要是是否允许为空了，我的想法是允许某一个是空串，但不能两个都是空的，你怎么看？
另外稍微规范一下错误码吧，explain是解释用的，接口只包含`code`和`message`
|code|message|explain|
|-|-|-|
|400|DOC_EXISTED|添加/更新文档标题冲突|
|401|DOC_NOT_FOUND|更新文档失败，文档未找到(可能已删除)|

然后可以的话记得`README`也更新一下

**Comment by buttercannfly** [comment]
- 可以，这个message设置感觉不错，我就按着这个写吧


| code | message | explain |
| -- | -- | -- |
| 400 | DOC_EXISTED | 添加/更新文档标题冲突 |
| 401 | DOC_NOT_FOUND | 更新文档失败，文档未找到(可能已删除) |
| 200 | SUCCESS | 操作正常 |
> 日后有其他返回码再更新
- 我记得title是数据库的主键，如果说是title空，paragraph非空的话，那么后台可以把paragraph的前五位当做title存进数据库；如果title非空，paragraph空，可以直接存进数据库不做其他处理

**Comment by EricJeffrey** [comment]
title是主键，那就不能为空了。那就按照**title不能为空，para可以为空**处理吧。

**Comment by buttercannfly** [comment]
ok

**Comment by EricJeffrey** [comment]
closed by #3
